import { 
    FaPhone, 
    FaEnvelope, 
    FaMapMarkerAlt, 
    FaGlobe, 
    FaClock, 
    FaParking, 
    FaWifi, 
    FaCreditCard, 
    FaAccessibleIcon, 
    FaUtensils, 
    FaCocktail, 
    FaCoffee, 
    FaBed, 
    FaSwimmingPool, 
    FaConciergeBell,
    FaFacebook,
    FaTwitter,
    FaInstagram,
    FaLinkedin,
    FaYoutube,
    FaShoppingCart,
    FaTshirt,
    FaBook,
    FaCar,
    FaPlane,
    FaTrain,
    FaBus,
    FaBicycle,
    FaHospital,
    FaGraduationCap,
    FaDumbbell,
    FaTheaterMasks,
    FaMusic,
    FaPaintBrush,
    FaCamera,
    FaGamepad,
    FaPaw,
    FaBabyCarriage,
    FaToolbox,
    FaCut,
    FaSpa,
    FaPizzaSlice,
    FaBeer,
    FaWineGlass,
    FaIceCream
  } from 'react-icons/fa';
  import { FaCheck } from "react-icons/fa6";

  
  export const businessIcons = [
    { name: 'Phone', icon: FaPhone },
    { name: 'Email', icon: FaEnvelope },
    { name: 'Location', icon: FaMapMarkerAlt },
    { name: 'Website', icon: FaGlobe },
    { name: 'Hours', icon: FaClock },
    { name: 'Parking', icon: FaParking },
    { name: 'Wi-Fi', icon: FaWifi },
    { name: 'Credit Card', icon: FaCreditCard },
    { name: 'Accessibility', icon: FaAccessibleIcon },
    { name: 'Restaurant', icon: FaUtensils },
    { name: 'Bar', icon: FaCocktail },
    { name: 'Cafe', icon: FaCoffee },
    { name: 'Hotel', icon: FaBed },
    { name: 'Pool', icon: FaSwimmingPool },
    { name: 'Concierge', icon: FaConciergeBell },
    { name: 'Facebook', icon: FaFacebook },
    { name: 'Twitter', icon: FaTwitter },
    { name: 'Instagram', icon: FaInstagram },
    { name: 'LinkedIn', icon: FaLinkedin },
    { name: 'YouTube', icon: FaYoutube },
    { name: 'Shopping', icon: FaShoppingCart },
    { name: 'Clothing', icon: FaTshirt },
    { name: 'Book', icon: FaBook },
    { name: 'Car', icon: FaCar },
    { name: 'Plane', icon: FaPlane },
    { name: 'Train', icon: FaTrain },
    { name: 'Bus', icon: FaBus },
    { name: 'Bicycle', icon: FaBicycle },
    { name: 'Hospital', icon: FaHospital },
    { name: 'Education', icon: FaGraduationCap },
    { name: 'Gym', icon: FaDumbbell },
    { name: 'Theater', icon: FaTheaterMasks },
    { name: 'Music', icon: FaMusic },
    { name: 'Art', icon: FaPaintBrush },
    { name: 'Camera', icon: FaCamera },
    { name: 'Gaming', icon: FaGamepad },
    { name: 'Pet', icon: FaPaw },
    { name: 'Baby', icon: FaBabyCarriage },
    { name: 'Tools', icon: FaToolbox },
    { name: 'Salon', icon: FaCut },
    { name: 'Spa', icon: FaSpa },
    { name: 'Pizza', icon: FaPizzaSlice },
    { name: 'Beer', icon: FaBeer },
    { name: 'Wine', icon: FaWineGlass },
    { name: 'Ice Cream', icon: FaIceCream },
    { name: 'Check', icon: FaCheck },
    
  ];